otel:
  enable:
    tick: true
    entities: true
    chunks: true
    tpsMspt: true
  preferSpark: true
  entitiesByChunk:
    mode: off
sampling:
  intervalSeconds: 1
  baselineScanIntervalSeconds: 10
